DATA SEGMENT

DATA ENDS
EXTRA SEGMENT

EXTRA ENDS
CODE SEGMENT
  ASSUME CS:CODE, DS:DATA, ES:EXTRA
  INCLUDE MainUtils.INC
  INCLUDE LString.INC
  MAIN:
    CALL MAIN_SETUP
    IS_LOWER_CHAR 'A'
    IS_LOWER_CHAR 't'
    IS_UPPER_CHAR 'O'
    CALL MAIN_END     
CODE ENDS
END MAIN