DATA SEGMENT
    
DATA ENDS
EXTRA SEGMENT

EXTRA ENDS
CODE SEGMENT
  ASSUME CS:CODE, DS:DATA, ES:EXTRA
  INCLUDE MainUtils.INC
  INCLUDE EMU8086.INC
  MAIN:
    CALL MAIN_SETUP
    PUTC 'A'
    PUTC 0AH
    PRINTN "Hello World!"
    PRINT "MY NAME IS KEN ROTHS"
    CALL MAIN_END     
CODE ENDS
END MAIN