DATA SEGMENT
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, 889AH
    MOV BX, 99AFH
    MOV CX, 5FABH
    MOV DX, 7779H
    JMP RESET_ALL_REG
    ;XOR DX, DX
    ;JNZ CONTINUE
RESET_ALL_REG:
    XOR AX, AX
    XOR BX, BX
    XOR CX, CX
    XOR DX, DX
CONTINUE:
    ;NOTHING
    
CODE ENDS
END START