DATA SEGMENT
    
DATA ENDS
EXTRA SEGMENT

EXTRA ENDS
CODE SEGMENT
  ASSUME CS:CODE, DS:DATA, ES:EXTRA
  INCLUDE MainUtils.INC
  INCLUDE CountUtils.INC
  MAIN:
    CALL MAIN_SETUP
    MOV BX, 88H
    CALL CTBBL
    MOV AL, DL
    CALL CFBBL 
    CALL MAIN_END     
CODE ENDS
END MAIN