DATA SEGMENT
      
DATA ENDS

CODE SEGMENT
  ASSUME CS:CODE, DS:DATA 
  INCLUDE gpr_utils.inc  
  MAIN:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV DX, 88AFH
    CALL RESET_GPR
    INT 21H     
CODE ENDS
END MAIN