DATA SEGMENT
    NUM DB 10h, 88h
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AL, [NUM]      ; AL = 10h
    MOV AH, [NUM + 1]  ; AH = 88h
    MOV AH, 4Ch
    INT 21h
CODE ENDS
END START