ORG 100H
MOV CX, COUNT ;SET OUTER LOOP COUNT
L1: INC BL ; BL = BL + 1
MOV COUNT, CX ; SAVE OUTER LOOP COUNT
MOV CX, 2 ; SET INNER LOOP COUNT
L2: INC AL ; AL = AL + 1
LOOP L2 ; REPEAT THE INNER LOOP
MOV CX, COUNT ; RESTORE OUTER LOOP COUNT
LOOP L1 ; REPEAT THE OUTER LOOP
INT 21H ; RETURNE THE CONTROL TO THE OPERATING SYSTEM
COUNT DW 5