RESET_ALL_REGSTER SEGMENT 
    XOR AX, AX
    XOR BX, BX
    XOR CX, CX
    XOR DX, DX
RESET_ALL_REGSTER ENDS
MOV AL, A[0]
MOV AH, A[1]
XCHG AX, B[1]
MOV A[0], AL
MOV A[1], AH
XOR AX, AX
MOV CL, A[0]
MOV DL, A[1]
MOV BX, B[1]
 RESET_ALL_REGSTER 
RET
A DB 17H, 28H, 33H, 93H, 98H
B DW 9588H, 6293H, 33FFH
C DB 10 DUP <0FH>
